# Imagen base para SDK de .NET (usado para construir la app)
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copiar los archivos del proyecto y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar todo el contenido y compilar
COPY . ./
RUN dotnet publish -c Release -o /out

# Imagen base para ejecutar la app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copiar los archivos publicados desde la etapa anterior
COPY --from=build-env /out .

# Exponer el puerto en el que correrá la app
EXPOSE 80

# Comando para ejecutar la aplicación
ENTRYPOINT ["dotnet", "MiProyectoApi.dll"]
